name: CMake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          find apps lib test -type f \( -name "*.hpp" -o -name "*.cpp" \) -exec clang-format --dry-run --Werror {} +

  build-and-test:
    runs-on: ubuntu-latest
    needs: clang-format  # Ensure clang-format runs first
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: ./build
        run: cmake .. -Dmonkey_compiler_ENABLE_TESTING=ON

      - name: Build project
        working-directory: ./build
        run: cmake --build . --config Release

      - name: Run tests
        working-directory: ./build
        run: ./test/monkey_compiler_unit_tests